rmRunCmd:
	@rm -f RunCmd

RunCmd: rmRunCmd 
	@gcc $@.c -o $@

rmShell:
	@rm -f Log710Shell

Log710Shell: rmShell
	@gcc $@.c -lpthread -o $@

rmShell2:
	@rm -f Log710Shell2

Log710Shell2: rmShell2
	@gcc $@.c -lpthread -o $@
